"""adicionar_modelos_cor_tamanho_variacao

Revision ID: 613aca5faec9
Revises: b1c2d3e4f5a6
Create Date: 2026-08-18 10:18:01.539730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '613aca5faec9'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo_hex', sa.String(length=9), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cores_id'), 'cores', ['id'], unique=False)
    op.create_index(op.f('ix_cores_nome'), 'cores', ['nome'], unique=True)
    op.create_table('tamanhos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tamanhos_id'), 'tamanhos', ['id'], unique=False)
    op.create_index(op.f('ix_tamanhos_nome'), 'tamanhos', ['nome'], unique=True)
    op.create_table('produto_variacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('cor_id', sa.Integer(), nullable=True),
    sa.Column('tamanho_id', sa.Integer(), nullable=True),
    sa.Column('estoque_atual', sa.Integer(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cor_id'], ['cores.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tamanho_id'], ['tamanhos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'cor_id', 'tamanho_id', name='uq_produto_cor_tamanho')
    )
    op.create_index(op.f('ix_produto_variacoes_id'), 'produto_variacoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produto_variacoes_id'), table_name='produto_variacoes')
    op.drop_table('produto_variacoes')
    op.drop_index(op.f('ix_tamanhos_nome'), table_name='tamanhos')
    op.drop_index(op.f('ix_tamanhos_id'), table_name='tamanhos')
    op.drop_table('tamanhos')
    op.drop_index(op.f('ix_cores_nome'), table_name='cores')
    op.drop_index(op.f('ix_cores_id'), table_name='cores')
    op.drop_table('cores')
    # ### end Alembic commands ###
