"""adicionar_coluna_imagem_variacao

Revision ID: 9fc710bced1a
Revises: 613aca5faec9
Create Date: 2026-08-18 10:23:42.639066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc710bced1a'
down_revision: Union[str, Sequence[str], None] = '613aca5faec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto_variacoes', sa.Column('imagem', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto_variacoes', 'imagem')
    # ### end Alembic commands ###
