"""recriando as tabelas

Revision ID: de3a912672ad
Revises: 51255561be96
Create Date: 2026-06-02 11:24:35.857300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de3a912672ad'
down_revision: Union[str, Sequence[str], None] = '51255561be96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_vendas_id'), table_name='itens_vendas')
    op.drop_table('itens_vendas')
    op.drop_index(op.f('ix_conquistas_id'), table_name='conquistas')
    op.drop_table('conquistas')
    op.drop_index(op.f('ix_vendas_id'), table_name='vendas')
    op.drop_table('vendas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('total', sa.FLOAT(), nullable=False),
    sa.Column('xp_ganho', sa.INTEGER(), nullable=False),
    sa.Column('desconto_aplicado', sa.FLOAT(), nullable=False),
    sa.Column('metodos_pagamento', sa.VARCHAR(length=255), nullable=False),
    sa.Column('data_venda', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendas_id'), 'vendas', ['id'], unique=False)
    op.create_table('conquistas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=167), nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=255), nullable=False),
    sa.Column('xp_requerido', sa.INTEGER(), nullable=False),
    sa.Column('desconto_reais', sa.FLOAT(), nullable=False),
    sa.Column('icon', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_conquistas_id'), 'conquistas', ['id'], unique=False)
    op.create_table('itens_vendas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('venda_id', sa.INTEGER(), nullable=False),
    sa.Column('produto_id', sa.INTEGER(), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=False),
    sa.Column('preco_unitario', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_vendas_id'), 'itens_vendas', ['id'], unique=False)
    # ### end Alembic commands ###
