"""adicionar tabelas produto e categoria

Revision ID: e49dbd68fa45
Revises: 453d0bd290e0
Create Date: 2026-05-26 16:32:46.359965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e49dbd68fa45'
down_revision: Union[str, Sequence[str], None] = '453d0bd290e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=167), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=167), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('estoque_atual', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('imagem_path', sa.String(length=255), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=False)
    op.alter_column('usuarios', 'nome',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=167),
               existing_nullable=False)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=167),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'email',
               existing_type=sa.String(length=167),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('usuarios', 'nome',
               existing_type=sa.String(length=167),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
